[package]
name = "defenestrator"
version = "1.0.1"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
description = "Simple asynchronous and multithreaded Minecraft name availability checker"

[dependencies]
anyhow = "1.0.53"
console = "0.15.0"
futures = "0.3.21"
lazy_static = "1.4.0"
parking_lot = "0.12.0"
regex = "1.5.4"
reqwest = "0.11.9"
structopt = "0.3.26"
tokio = { version = "1.16.1", features = ["full"] }
