[package]
name = "defenestrator"
version = "1.0.0"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
description = "Simple asynchronous and multithreaded Minecraft name availability checker"

[dependencies]
anyhow = "1.0"
console = "0.15"
futures = "0.3"
lazy_static = "1.4"
regex = "1.5"
reqwest = { version = "0.11", default_features = false, features = ["rustls-tls-native-roots"] }
structopt = "0.3"
tokio = { version = "1.14", features = ["full"] }

[profile.release]
lto = "fat"
codegen-units = 1
