[package]
name = "defenestrator"
version = "1.0.1"
edition = "2021"
authors = ["tropicbliss <tropicbliss@protonmail.com>"]
description = "Simple asynchronous and multithreaded Minecraft name availability checker"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive"] }
futures = "0.3.21"
lazy_static = "1.4.0"
parking_lot = "0.12.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", default_features = false, features = ["rustls-tls"] }
tokio = { version = "1.16.1", features = ["full"] }
